development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pond_development
  pool: 5
  username: root
  password: 7102531k
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pond_test
  pool: 5
  username: root
  password: 7102531k
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pond_production
  pool: 4
  username: root
  password: 7102531k
  host: localhost
