require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MonthlyRecodesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # MonthlyRecode. As you add validations to MonthlyRecode, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MonthlyRecodesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all monthly_recodes as @monthly_recodes" do
      monthly_recode = MonthlyRecode.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:monthly_recodes)).to eq([monthly_recode])
    end
  end

  describe "GET show" do
    it "assigns the requested monthly_recode as @monthly_recode" do
      monthly_recode = MonthlyRecode.create! valid_attributes
      get :show, {:id => monthly_recode.to_param}, valid_session
      expect(assigns(:monthly_recode)).to eq(monthly_recode)
    end
  end

  describe "GET new" do
    it "assigns a new monthly_recode as @monthly_recode" do
      get :new, {}, valid_session
      expect(assigns(:monthly_recode)).to be_a_new(MonthlyRecode)
    end
  end

  describe "GET edit" do
    it "assigns the requested monthly_recode as @monthly_recode" do
      monthly_recode = MonthlyRecode.create! valid_attributes
      get :edit, {:id => monthly_recode.to_param}, valid_session
      expect(assigns(:monthly_recode)).to eq(monthly_recode)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MonthlyRecode" do
        expect {
          post :create, {:monthly_recode => valid_attributes}, valid_session
        }.to change(MonthlyRecode, :count).by(1)
      end

      it "assigns a newly created monthly_recode as @monthly_recode" do
        post :create, {:monthly_recode => valid_attributes}, valid_session
        expect(assigns(:monthly_recode)).to be_a(MonthlyRecode)
        expect(assigns(:monthly_recode)).to be_persisted
      end

      it "redirects to the created monthly_recode" do
        post :create, {:monthly_recode => valid_attributes}, valid_session
        expect(response).to redirect_to(MonthlyRecode.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved monthly_recode as @monthly_recode" do
        post :create, {:monthly_recode => invalid_attributes}, valid_session
        expect(assigns(:monthly_recode)).to be_a_new(MonthlyRecode)
      end

      it "re-renders the 'new' template" do
        post :create, {:monthly_recode => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested monthly_recode" do
        monthly_recode = MonthlyRecode.create! valid_attributes
        put :update, {:id => monthly_recode.to_param, :monthly_recode => new_attributes}, valid_session
        monthly_recode.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested monthly_recode as @monthly_recode" do
        monthly_recode = MonthlyRecode.create! valid_attributes
        put :update, {:id => monthly_recode.to_param, :monthly_recode => valid_attributes}, valid_session
        expect(assigns(:monthly_recode)).to eq(monthly_recode)
      end

      it "redirects to the monthly_recode" do
        monthly_recode = MonthlyRecode.create! valid_attributes
        put :update, {:id => monthly_recode.to_param, :monthly_recode => valid_attributes}, valid_session
        expect(response).to redirect_to(monthly_recode)
      end
    end

    describe "with invalid params" do
      it "assigns the monthly_recode as @monthly_recode" do
        monthly_recode = MonthlyRecode.create! valid_attributes
        put :update, {:id => monthly_recode.to_param, :monthly_recode => invalid_attributes}, valid_session
        expect(assigns(:monthly_recode)).to eq(monthly_recode)
      end

      it "re-renders the 'edit' template" do
        monthly_recode = MonthlyRecode.create! valid_attributes
        put :update, {:id => monthly_recode.to_param, :monthly_recode => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested monthly_recode" do
      monthly_recode = MonthlyRecode.create! valid_attributes
      expect {
        delete :destroy, {:id => monthly_recode.to_param}, valid_session
      }.to change(MonthlyRecode, :count).by(-1)
    end

    it "redirects to the monthly_recodes list" do
      monthly_recode = MonthlyRecode.create! valid_attributes
      delete :destroy, {:id => monthly_recode.to_param}, valid_session
      expect(response).to redirect_to(monthly_recodes_url)
    end
  end

end
