require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe UnitMissionsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # UnitMission. As you add validations to UnitMission, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UnitMissionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all unit_missions as @unit_missions" do
      unit_mission = UnitMission.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:unit_missions)).to eq([unit_mission])
    end
  end

  describe "GET show" do
    it "assigns the requested unit_mission as @unit_mission" do
      unit_mission = UnitMission.create! valid_attributes
      get :show, {:id => unit_mission.to_param}, valid_session
      expect(assigns(:unit_mission)).to eq(unit_mission)
    end
  end

  describe "GET new" do
    it "assigns a new unit_mission as @unit_mission" do
      get :new, {}, valid_session
      expect(assigns(:unit_mission)).to be_a_new(UnitMission)
    end
  end

  describe "GET edit" do
    it "assigns the requested unit_mission as @unit_mission" do
      unit_mission = UnitMission.create! valid_attributes
      get :edit, {:id => unit_mission.to_param}, valid_session
      expect(assigns(:unit_mission)).to eq(unit_mission)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UnitMission" do
        expect {
          post :create, {:unit_mission => valid_attributes}, valid_session
        }.to change(UnitMission, :count).by(1)
      end

      it "assigns a newly created unit_mission as @unit_mission" do
        post :create, {:unit_mission => valid_attributes}, valid_session
        expect(assigns(:unit_mission)).to be_a(UnitMission)
        expect(assigns(:unit_mission)).to be_persisted
      end

      it "redirects to the created unit_mission" do
        post :create, {:unit_mission => valid_attributes}, valid_session
        expect(response).to redirect_to(UnitMission.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved unit_mission as @unit_mission" do
        post :create, {:unit_mission => invalid_attributes}, valid_session
        expect(assigns(:unit_mission)).to be_a_new(UnitMission)
      end

      it "re-renders the 'new' template" do
        post :create, {:unit_mission => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested unit_mission" do
        unit_mission = UnitMission.create! valid_attributes
        put :update, {:id => unit_mission.to_param, :unit_mission => new_attributes}, valid_session
        unit_mission.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested unit_mission as @unit_mission" do
        unit_mission = UnitMission.create! valid_attributes
        put :update, {:id => unit_mission.to_param, :unit_mission => valid_attributes}, valid_session
        expect(assigns(:unit_mission)).to eq(unit_mission)
      end

      it "redirects to the unit_mission" do
        unit_mission = UnitMission.create! valid_attributes
        put :update, {:id => unit_mission.to_param, :unit_mission => valid_attributes}, valid_session
        expect(response).to redirect_to(unit_mission)
      end
    end

    describe "with invalid params" do
      it "assigns the unit_mission as @unit_mission" do
        unit_mission = UnitMission.create! valid_attributes
        put :update, {:id => unit_mission.to_param, :unit_mission => invalid_attributes}, valid_session
        expect(assigns(:unit_mission)).to eq(unit_mission)
      end

      it "re-renders the 'edit' template" do
        unit_mission = UnitMission.create! valid_attributes
        put :update, {:id => unit_mission.to_param, :unit_mission => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested unit_mission" do
      unit_mission = UnitMission.create! valid_attributes
      expect {
        delete :destroy, {:id => unit_mission.to_param}, valid_session
      }.to change(UnitMission, :count).by(-1)
    end

    it "redirects to the unit_missions list" do
      unit_mission = UnitMission.create! valid_attributes
      delete :destroy, {:id => unit_mission.to_param}, valid_session
      expect(response).to redirect_to(unit_missions_url)
    end
  end

end
